version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check for updates every Monday
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "deps: ", which should be
      # accepted as a conventional commit and trigger release-please
      prefix: "deps"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
