site_name: DeepBioP User Guide
repo_url: https://github.com/cauliyang/DeepBioP
repo_name: cauliyang/DeepBioP
copyright: Copyright &copy; 2023 - 2024 Yangyang Li

nav:
  - User guide:
      - index.md
      - user-guide/getting-started.md
      - user-guide/installation.md
      - Development:
          - Contributing:
              - development/contributing/index.md
              - development/contributing/ide.md
              - development/contributing/test.md
              - development/contributing/ci.md
              - development/contributing/code-style.md
          - development/versioning.md
  - API reference:
      - api/index.md
  - About:
      - License: license.md

# Build directories
theme:
  name: material
  locale: en
  font:
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # logo: _build/assets/logo.png
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.indexes
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - toc.integrate
    - toc.follow
  icon:
    repo: fontawesome/brands/git-alt

plugins:
  - social
  - search:
      lang: en
  - git-committers:
      repository: cauliyang/DeepBioP
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cauliyang/DeepBioP
    - icon: fontawesome/solid/paper-plane
      link: mailto:yangyang.li@northwestern.edu

# Formatting options
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
