# This file is automatically generated by pyo3_stub_gen

import builtins
import typing

__all__ = [
    "Compose",
    "DataLoader",
    "DataLoaderIterator",
    "Dataset",
    "DatasetIterator",
    "IntegerEncoder",
    "KmerEncoder",
    "Mutator",
    "OneHotEncoder",
    "ReverseComplement",
    "Sampler",
    "default_collate",
    "is_cache_valid",
    "load_cache",
    "save_cache",
]

@typing.final
class Compose:
    r"""Compose multiple transforms sequentially.

    Chains transforms by calling them in order on the sample.
    Similar to torchvision.transforms.Compose.
    """
    def __new__(cls, transforms: typing.Sequence[typing.Any]) -> Compose:
        r"""Create a new Compose transform.

        Args:
            transforms: List of transform callables

        Returns:
            Compose instance
        """
    def __call__(self, sample: typing.Any) -> typing.Any:
        r"""Apply all transforms sequentially.

        Args:
            sample: Sample dict

        Returns:
            Transformed sample after applying all transforms
        """
    def __repr__(self) -> builtins.str:
        r"""Human-readable representation."""

@typing.final
class DataLoader:
    r"""PyTorch-compatible DataLoader for batching and shuffling.

    Wraps Dataset to provide:
    - __len__(): Returns number of batches
    - __iter__(): Returns iterator over batches
    - Batching with configurable batch_size
    - Optional shuffling with seed control
    """
    def __new__(
        cls,
        dataset: Dataset,
        *,
        batch_size: builtins.int = 1,
        shuffle: builtins.bool = False,
        collate_fn: typing.Any | None = None,
        drop_last: builtins.bool = False,
        seed: builtins.int | None = None,
    ) -> DataLoader:
        r"""Create a new DataLoader.

        Args:
            dataset: Dataset instance to load from
            batch_size: Number of samples per batch (default: 1)
            shuffle: Whether to shuffle data (default: False)
            collate_fn: Callable receiving the list of samples of a batch and
                returning the batch object (e.g. `deepbiop.pytorch.default_collate`).
                When None, each batch is the plain list of samples.
            drop_last: Drop last incomplete batch (default: False)
            seed: Random seed for shuffling (default: None)

        This loader runs in-process. For multi-process loading use
        `torch.utils.data.DataLoader` on top of the dataset instead.

        Returns:
            DataLoader instance
        """
    def __len__(self) -> builtins.int:
        r"""Returns number of batches.

        Calculated as:
        - If drop_last=False: ceil(dataset_size / batch_size)
        - If drop_last=True: floor(dataset_size / batch_size)
        """
    def __iter__(self) -> DataLoaderIterator:
        r"""Iterate over batches.

        Returns:
            Iterator over batches (each batch is a list of samples, or the
            result of `collate_fn` applied to that list)
        """
    def __repr__(self) -> builtins.str:
        r"""Human-readable representation."""

@typing.final
class DataLoaderIterator:
    r"""Iterator for DataLoader.

    Maintains iteration state and yields batches as lists of samples.
    """
    def __iter__(self) -> DataLoaderIterator: ...
    def __next__(self) -> typing.Any | None: ...

@typing.final
class Dataset:
    r"""PyTorch-compatible map-style Dataset for FASTQ files.

    - `__len__()`: number of records
    - `__getitem__(i)`: `{"sequence": bytes, "quality": bytes}` (after `transform`, if any)
    - `__iter__()`: sequential iteration
    """
    def __new__(
        cls,
        file_path: builtins.str,
        *,
        sequence_type: builtins.str = "dna",
        transform: typing.Any | None = None,
    ) -> Dataset:
        r"""Create a new Dataset from a FASTQ file (plain, gzip or bgzip).

        Args:
            file_path: Path to the FASTQ file
            sequence_type: "dna", "rna" or "protein"; recorded for downstream encoders
            transform: Optional callable applied to every sample dict returned by
                `__getitem__`/iteration (e.g. an encoder or `Compose`)

        Raises:
            FileNotFoundError: If the file does not exist
            IOError: If the file cannot be parsed
        """
    def __len__(self) -> builtins.int:
        r"""Returns total number of sequences in dataset."""
    def __getitem__(self, idx: builtins.int) -> typing.Any:
        r"""Get sample at index idx.

        Args:
            idx: Sample index (0 to len(dataset)-1)

        Returns:
            Sample dict with 'sequence' and 'quality' keys, passed through
            `transform` when one was given.

        Raises:
            IndexError: If idx out of range
        """
    def __iter__(self) -> DatasetIterator:
        r"""Iterate over all samples in dataset."""
    def __repr__(self) -> builtins.str:
        r"""Human-readable representation."""
    def summary(self) -> dict:
        r"""Get dataset statistics.

        Returns:
            Dict with keys:
                - 'num_samples': int - Total number of sequences
                - 'length_stats': dict - Statistics with 'min', 'max', 'mean', 'median' sequence lengths
                - 'memory_footprint': int - Estimated memory usage in bytes (sequence + quality)
        """
    def validate(self) -> dict:
        r"""Validate dataset quality and integrity on the first 10 records.

        Returns:
            Dict with keys 'is_valid' (bool), 'warnings' (list[str]), 'errors' (list[str])
        """

@typing.final
class DatasetIterator:
    r"""Iterator for Dataset."""
    def __iter__(self) -> DatasetIterator: ...
    def __next__(self) -> typing.Any | None: ...

@typing.final
class IntegerEncoder:
    r"""PyTorch-compatible IntegerEncoder transform.

    Wraps deepbiop.fq.IntegerEncoder to provide Transform protocol:
    - __call__(sample) -> sample with encoded sequence
    - __repr__() for debugging
    """
    def __new__(cls, encoding_type: builtins.str = "dna") -> IntegerEncoder:
        r"""Create a new IntegerEncoder.

        Args:
            encoding_type: Sequence type ("dna", "rna", "protein")

        Returns:
            IntegerEncoder instance

        Raises:
            ValueError: If encoding_type is invalid
        """
    def __call__(self, sample: dict) -> dict:
        r"""Apply integer encoding to sample['sequence'].

        Args:
            sample: Sample dict with 'sequence' key (bytes)

        Returns:
            Sample dict with 'sequence' encoded as NumPy array

        Raises:
            ValueError: If sample missing 'sequence' key or encoding fails
        """
    def __repr__(self) -> builtins.str:
        r"""Human-readable representation."""

@typing.final
class KmerEncoder:
    r"""PyTorch-compatible KmerEncoder transform.

    Wraps deepbiop.core.KmerEncoder to provide Transform protocol:
    - __call__(sample) -> sample with encoded sequence
    - __repr__() for debugging
    """
    def __new__(
        cls,
        k: builtins.int = 3,
        canonical: builtins.bool = False,
        encoding_type: builtins.str = "dna",
    ) -> KmerEncoder:
        r"""Create a new KmerEncoder.

        Args:
            k: K-mer length
            canonical: Whether to use canonical k-mers
            encoding_type: Sequence type ("dna", "rna", "protein")

        Returns:
            KmerEncoder instance

        Raises:
            ValueError: If k or encoding_type is invalid
        """
    def __call__(self, sample: dict) -> dict:
        r"""Apply k-mer encoding to sample['sequence'].

        Args:
            sample: Sample dict with 'sequence' key (bytes)

        Returns:
            Sample dict with 'sequence' encoded as NumPy array (k-mer frequency vector)

        Raises:
            ValueError: If sample missing 'sequence' key or encoding fails
        """
    def __repr__(self) -> builtins.str:
        r"""Human-readable representation."""

@typing.final
class Mutator:
    r"""PyTorch-compatible Mutator transform.

    Wraps deepbiop.fq.Mutator to provide Transform protocol.
    """
    def __new__(
        cls, mutation_rate: builtins.float, seed: builtins.int | None = None
    ) -> Mutator:
        r"""Create a new Mutator transform.

        Args:
            mutation_rate: Probability of mutation per base
            seed: Optional random seed for reproducibility

        Returns:
            Mutator instance
        """
    def __call__(self, sample: dict) -> dict:
        r"""Apply mutation to sample['sequence'].

        Args:
            sample: Sample dict with 'sequence' key (bytes)

        Returns:
            Sample dict with mutated sequence
        """
    def __repr__(self) -> builtins.str:
        r"""Human-readable representation."""

@typing.final
class OneHotEncoder:
    r"""PyTorch-compatible OneHotEncoder transform.

    Wraps deepbiop.fq.OneHotEncoder to provide Transform protocol:
    - __call__(sample) -> sample with encoded sequence
    - __repr__() for debugging
    """
    def __new__(
        cls,
        encoding_type: builtins.str = "dna",
        unknown_strategy: builtins.str = "skip",
        seed: builtins.int | None = None,
    ) -> OneHotEncoder:
        r"""Create a new OneHotEncoder.

        Args:
            encoding_type: Sequence type ("dna", "rna", "protein") - default: "dna"
            unknown_strategy: How to handle unknown bases ("skip", "mask", "random") - default: "skip"
            seed: Optional random seed for reproducible random replacements - default: None

        Returns:
            OneHotEncoder instance

        Raises:
            ValueError: If encoding_type or unknown_strategy is invalid

        Examples:
            >>> encoder = OneHotEncoder()
            >>> encoder = OneHotEncoder(
            ...     encoding_type="rna", unknown_strategy="mask", seed=42
            ... )
        """
    def __call__(self, sample: dict) -> dict:
        r"""Apply one-hot encoding to sample['sequence'].

        Args:
            sample: Sample dict with 'sequence' key (bytes)

        Returns:
            Sample dict with 'sequence' encoded as NumPy array

        Raises:
            ValueError: If sample missing 'sequence' key or encoding fails
        """
    def __repr__(self) -> builtins.str:
        r"""Human-readable representation."""

@typing.final
class ReverseComplement:
    r"""PyTorch-compatible ReverseComplement transform.

    Wraps deepbiop.fq.ReverseComplement to provide Transform protocol.
    """
    def __new__(cls) -> ReverseComplement:
        r"""Create a new ReverseComplement transform.

        Returns:
            ReverseComplement instance
        """
    def __call__(self, sample: dict) -> dict:
        r"""Apply reverse complement to sample['sequence'].

        Args:
            sample: Sample dict with 'sequence' key (bytes)

        Returns:
            Sample dict with reverse complemented sequence
        """
    def __repr__(self) -> builtins.str:
        r"""Human-readable representation."""

@typing.final
class Sampler:
    r"""PyTorch-compatible Sampler transform.

    Wraps deepbiop.fq.Sampler to provide Transform protocol.
    """
    def __new__(
        cls,
        length: builtins.int,
        strategy: builtins.str = "start",
        seed: builtins.int | None = None,
    ) -> Sampler:
        r"""Create a new Sampler transform.

        Args:
            length: Target length to sample
            strategy: Sampling strategy ("start", "center", "end", "random")
            seed: Optional random seed for reproducible random sampling

        Returns:
            Sampler instance
        """
    def __call__(self, sample: dict) -> dict:
        r"""Apply sampling to sample['sequence'].

        Args:
            sample: Sample dict with 'sequence' key (bytes)

        Returns:
            Sample dict with sampled sequence
        """
    def __repr__(self) -> builtins.str:
        r"""Human-readable representation."""

def default_collate(samples: list) -> dict:
    r"""Default collate function for batching variable-length sequences.

    Takes a list of samples (each with 'sequence' as 2D NumPy array) and:
    1. Finds maximum sequence length in the batch
    2. Pads all sequences to max_length with zeros
    3. Stacks into batch array [batch_size, max_len, features]
    4. Records original lengths for masking/packing

    Args:
        samples: List of sample dicts, each with 'sequence' key (2D NumPy float32 array)

    Returns:
        Batch dict with:
        - 'sequences': NumPy array of shape [batch_size, max_len, features]
        - 'lengths': NumPy array of original sequence lengths (1D int32)
        - Other sample keys preserved as lists (e.g., 'quality', 'metadata')

    Raises:
        ValueError: If samples list is empty, missing 'sequence' key, or sequences have inconsistent feature dimensions

    Examples:
        >>> batch = default_collate([sample1, sample2, sample3])
        >>> batch["sequences"].shape
        (3, 150, 4)  # 3 samples, padded to 150bp, 4 features (one-hot DNA)
    """

def is_cache_valid(
    cache_path: builtins.str, source_file: builtins.str | None = None
) -> builtins.bool:
    r"""Check if a cache is present and not stale.

    Returns False if the cache or its metadata is missing, or if `source_file`
    is given and its size or modification time differ from what was recorded
    when the cache was written.

    Args:
        cache_path: Path to cache file (`.npz`)
        source_file: Source file path to check against (optional)

    Examples:
        >>> is_cache_valid("cache.npz", source_file="data.fastq")
        True
    """

def load_cache(cache_path: builtins.str) -> list:
    r"""Load processed samples from a cache file written by [`save_cache`].

    Args:
        cache_path: Path to cache file (`.npz`)

    Returns:
        List of sample dicts with the keys they were saved with; bytes values
        come back as `bytes`, everything else as NumPy arrays/scalars.

    Raises:
        FileNotFoundError: If cache or metadata file not found
        IOError: If load fails or file is corrupted

    Examples:
        >>> samples = load_cache("cache.npz")
        >>> len(samples)
        1000
    """

def save_cache(
    samples: list, cache_path: builtins.str, source_file: builtins.str | None = None
) -> None:
    r"""Save processed samples to a cache file.

    Every key of every sample dict is stored (NumPy arrays, bytes, numbers,
    strings), so a cached sample loads back with the same keys it was saved with.

    Args:
        samples: List of sample dicts; all samples must share the same keys
        cache_path: Path to the cache file (`.npz` is appended if missing)
        source_file: Optional source file path for staleness detection

    Raises:
        ValueError: If samples list is empty or samples have differing keys
        IOError: If file write fails

    Examples:
        >>> save_cache(processed_samples, "cache.npz", source_file="data.fastq")
    """
