# This file is automatically generated by pyo3_stub_gen

import builtins
import os
import pathlib
import typing

__all__ = [
    "Variant",
    "VcfReader",
]

@typing.final
class Variant:
    r"""Represents a genomic variant from a VCF file."""
    @property
    def chromosome(self) -> builtins.str: ...
    @property
    def position(self) -> builtins.int: ...
    @property
    def id(self) -> builtins.str | None: ...
    @property
    def reference_allele(self) -> builtins.str: ...
    @property
    def alternate_alleles(self) -> builtins.list[builtins.str]: ...
    @property
    def quality(self) -> builtins.float | None: ...
    @property
    def filter(self) -> builtins.list[builtins.str]: ...
    @property
    def info(self) -> builtins.dict[builtins.str, builtins.str]:
        r"""INFO fields as parsed from the record.

        One entry per key: flags as "true", arrays comma-joined, missing values as ".".
        """
    def is_snp(self) -> builtins.bool:
        r"""Check if variant is a SNP (single nucleotide polymorphism)."""
    def is_indel(self) -> builtins.bool:
        r"""Check if variant is an indel (insertion/deletion)."""
    def get_info_field(self, key: builtins.str) -> builtins.str | None:
        r"""Look up a single INFO field, or None when the record has no such key."""
    def passes_filter(self) -> builtins.bool:
        r"""Check if variant passes all filters."""
    def __repr__(self) -> builtins.str: ...

@typing.final
class VcfReader:
    r"""Python wrapper for VCF file reader."""
    def __new__(cls, path: builtins.str | os.PathLike | pathlib.Path) -> VcfReader:
        r"""Open a VCF file for reading.

        Args:
            path: Path to the VCF file

        Returns:
            VcfReader instance
        """
    def read_all(self) -> builtins.list[Variant]:
        r"""Read all variants from the file.

        Returns:
            List of Variant objects
        """
    def filter_by_quality(self, min_quality: builtins.float) -> builtins.list[Variant]:
        r"""Filter variants by minimum quality score.

        Args:
            min_quality: Minimum quality threshold

        Returns:
            List of variants meeting quality criteria
        """
    def filter_passing(self) -> builtins.list[Variant]:
        r"""Filter variants that pass all filters.

        Returns:
            List of passing variants
        """
