# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: F401

"""DeepBioP: Deep Learning Preprocessing Library for Biological Data.

A high-performance Python library for loading, preprocessing, and transforming
biological sequence data (FASTQ, FASTA, BAM, VCF, GTF) for deep learning workflows.
"""

from typing import Any

# Submodules (Rust extensions)
from deepbiop import bam, core, fa, fq, gtf, pytorch, utils, vcf

# Pure Python exports
from deepbiop.lightning import BiologicalDataModule
from deepbiop.transforms import Compose, FilterCompose, TransformDataset

__all__ = [
    # Pure Python classes
    "BiologicalDataModule",
    "Compose",
    "FilterCompose",
    "TransformDataset",
    # Submodules
    "bam",
    "core",
    "fa",
    "fq",
    "gtf",
    "pytorch",
    "utils",
    "vcf",
]

__version__: str
