# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

def left_right_soft_clip(cigar_string: str) -> tuple[int, int]:
    r"""Calculate left and right soft clips from a cigar string."""
