# This file is automatically generated by pyo3_stub_gen

import builtins
import os
import pathlib
import typing

def count_chimeric_reads_for_path(
    bam: builtins.str | os.PathLike | pathlib.Path, threads: builtins.int | None = None
) -> builtins.int:
    r"""Calculate the number of chimeric reads in a BAM file."""

def count_chimeric_reads_for_paths(
    bams: typing.Sequence[builtins.str | os.PathLike | pathlib.Path],
    threads: builtins.int | None = None,
) -> builtins.dict[pathlib.Path, builtins.int]:
    r"""Calculate the number of chimeric reads in multiple BAM files."""

def left_right_soft_clip(
    cigar_string: builtins.str,
) -> tuple[builtins.int, builtins.int]:
    r"""Calculate left and right soft clips from a cigar string."""
