# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing

def generate_kmers(base:str,k:int) -> list[str]:
    ...

def generate_kmers_table(base:str,k:int) -> dict[list[int], int]:
    ...

def kmers_to_seq(kmers:typing.Sequence[str]) -> str:
    ...

def normalize_seq(seq:str,iupac:bool) -> str:
    r"""
    Normalize a DNA sequence by converting any non-standard nucleotides to standard ones.

    This function takes a DNA sequence as a `String` and a boolean flag `iupac` indicating whether to normalize using IUPAC ambiguity codes.
    It returns a normalized DNA sequence as a `String`.

    # Arguments

    * `seq` - A DNA sequence as a `String`.
    * `iupac` - A boolean flag indicating whether to normalize using IUPAC ambiguity codes.

    # Returns

    A normalized DNA sequence as a `String`.
    """

def seq_to_kmers(seq:str,k:int,overlap:bool) -> list[str]:
    ...

