# This file is automatically generated by pyo3_stub_gen

import builtins
import os
import pathlib
import typing

@typing.final
class EncoderOption:
    r"""Options for configuring the FASTA sequence encoder.

    This struct provides configuration options for encoding FASTA sequences,
    such as which bases to consider during encoding.

    # Fields

    * `bases` - A vector of valid bases (as bytes) to use for encoding. Defaults to "ATCGN".

    # Example

    ```
    use deepbiop_fa::encode::option::EncoderOption;

    let options = EncoderOption::default();
    ```
    """

    @property
    def bases(self) -> builtins.list[builtins.int]: ...
    @bases.setter
    def bases(self, value: builtins.list[builtins.int]) -> None: ...
    def __new__(cls, bases: builtins.str) -> EncoderOption: ...

@typing.final
class ParquetEncoder:
    r"""An encoder for converting FASTA records to Parquet format.

    This struct provides functionality to encode FASTA sequence data into Parquet files,
    which are an efficient columnar storage format.

    # Fields

    * `option` - Configuration options for the encoder, including which bases to consider

    # Example

    ```
    use deepbiop_fa::encode::{option::EncoderOption, parquet::ParquetEncoder};

    let options = EncoderOption::default();
    let encoder = ParquetEncoder::new(options);
    ```
    """

    def __new__(cls, option: EncoderOption) -> ParquetEncoder: ...

@typing.final
class RecordData:
    @property
    def id(self) -> builtins.str: ...
    @id.setter
    def id(self, value: builtins.str) -> None: ...
    @property
    def seq(self) -> builtins.str: ...
    @seq.setter
    def seq(self, value: builtins.str) -> None: ...
    def __new__(cls, id: builtins.str, seq: builtins.str) -> RecordData: ...

def convert_multiple_fas_to_one_fa(
    paths: typing.Sequence[builtins.str | os.PathLike | pathlib.Path],
    result_path: builtins.str | os.PathLike | pathlib.Path,
    parallel: builtins.bool,
) -> None: ...
def encode_fa_path_to_parquet(
    fa_path: builtins.str | os.PathLike | pathlib.Path,
    bases: builtins.str,
    result_path: builtins.str | os.PathLike | pathlib.Path | None = None,
) -> None: ...
def encode_fa_path_to_parquet_chunk(
    fa_path: builtins.str | os.PathLike | pathlib.Path,
    chunk_size: builtins.int,
    parallel: builtins.bool,
    bases: builtins.str,
) -> None: ...
def encode_fa_paths_to_parquet(
    fa_path: typing.Sequence[builtins.str | os.PathLike | pathlib.Path],
    bases: builtins.str,
) -> None: ...
def select_record_from_fa(
    selected_reads: typing.Sequence[builtins.str],
    fq: builtins.str | os.PathLike | pathlib.Path,
    output: builtins.str | os.PathLike | pathlib.Path,
) -> None: ...
def select_record_from_fa_by_random(
    fq: builtins.str | os.PathLike | pathlib.Path,
    number: builtins.int,
    output: builtins.str | os.PathLike | pathlib.Path,
) -> None: ...
def write_fa(
    records_data: typing.Sequence[RecordData],
    file_path: builtins.str | os.PathLike | pathlib.Path | None = None,
) -> None: ...
def write_fa_parallel(
    records_data: typing.Sequence[RecordData],
    file_path: builtins.str | os.PathLike | pathlib.Path,
    threads: builtins.int,
) -> None: ...
def fasta_to_fastq(
    fasta_path: builtins.str | os.PathLike | pathlib.Path,
    fastq_path: builtins.str | os.PathLike | pathlib.Path,
) -> None:
    """Convert FASTA file to FASTQ file with default quality scores.

    Since FASTA files don't contain quality information, assigns
    default quality score (Phred+33 Q40 = '~') to all bases.
    Q40 represents 99.99% base call accuracy.

    Args:
        fasta_path: Path to input FASTA file
        fastq_path: Path to output FASTQ file
    """
