# This file is automatically generated by pyo3_stub_gen

import builtins
import os
import pathlib
import typing

@typing.final
class GtfReader:
    """Python wrapper for GTF file reader."""

    def __new__(cls, path: builtins.str | os.PathLike | pathlib.Path) -> GtfReader:
        """Open a GTF file for reading.

        Args:
            path: Path to the GTF file

        Returns:
            GtfReader instance
        """

    def read_all(self) -> builtins.list[GenomicFeature]:
        """Read all features from the file.

        Returns:
            List of GenomicFeature objects
        """

    def build_gene_index(
        self,
    ) -> builtins.dict[builtins.str, builtins.list[GenomicFeature]]:
        """Build an index of features by gene ID.

        Returns:
            Dictionary mapping gene IDs to lists of features
        """

    def filter_by_type(
        self, feature_type: builtins.str
    ) -> builtins.list[GenomicFeature]:
        """Filter features by type (e.g., "gene", "exon", "CDS").

        Args:
            feature_type: Feature type to filter for

        Returns:
            List of features of the specified type
        """

@typing.final
class GenomicFeature:
    """Represents a genomic feature from a GTF file."""

    @property
    def seqname(self) -> builtins.str: ...
    @property
    def source(self) -> builtins.str: ...
    @property
    def feature_type(self) -> builtins.str: ...
    @property
    def start(self) -> builtins.int: ...
    @property
    def end(self) -> builtins.int: ...
    @property
    def score(self) -> builtins.float | None: ...
    @property
    def strand(self) -> builtins.str: ...
    @property
    def frame(self) -> builtins.int | None: ...
    @property
    def attributes(self) -> builtins.dict[builtins.str, builtins.str]: ...
    def gene_id(self) -> builtins.str | None:
        """Get gene ID from attributes.

        Returns:
            Gene ID if present, None otherwise
        """

    def transcript_id(self) -> builtins.str | None:
        """Get transcript ID from attributes.

        Returns:
            Transcript ID if present, None otherwise
        """

    def gene_name(self) -> builtins.str | None:
        """Get gene name from attributes.

        Returns:
            Gene name if present, None otherwise
        """

    def length(self) -> builtins.int:
        """Get the length of the feature.

        Returns:
            Length in base pairs
        """

    def __repr__(self) -> builtins.str: ...
